//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntertainmentEntities : DbContext
    {
        public EntertainmentEntities()
            : base("name=EntertainmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Movie> Movies { get; set; }
    
        public virtual ObjectResult<sps_GetMovieRanking_Result> sps_GetMovieRanking()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sps_GetMovieRanking_Result>("sps_GetMovieRanking");
        }
    }
}
