//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public Nullable<int> Rank { get; set; }
        public bool DELETED { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_TIMESTAMP { get; set; }
        public System.DateTime CREATE_TIMESTAMP { get; set; }
        public string CREATED_BY { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
